version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: payflow-sql
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - payflow
    healthcheck:
      test: ["CMD", "/bin/bash", "-c", "echo 'SQL Server started'"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  redis:
    image: redis:8-alpine
    container_name: payflow-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - payflow
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  ml-service:
    build:
      context: ./ml-service
      dockerfile: Dockerfile
    container_name: payflow-ml
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - payflow
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/health').read()\""]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: src/PayFlow.Api/Dockerfile
    container_name: payflow-api
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=payflow;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=true
      - Redis__Configuration=redis:6379
      - FraudScoring__ServiceUrl=http://ml-service:8000
      - PaymentGateway__BaseUrl=http://localhost:5000
      - Cors__AllowedOrigins=http://localhost:5173
    depends_on:
      sqlserver:
        condition: service_healthy
      redis:
        condition: service_healthy
      ml-service:
        condition: service_healthy
    networks:
      - payflow

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: payflow-frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - api
    networks:
      - payflow

volumes:
  sqlserver_data:
  redis_data:

networks:
  payflow:
    driver: bridge
